language: java

services: docker

jdk: oraclejdk8
install:
  # installing dependencies and skipping docker push
  - mvn clean install -DskipDockerPush -Dmaven.test.skip=true  -Dmaven.site.skip=true -Dmaven.javadoc.skip=true

cache:
  directories:
  - $HOME/.m2

script:
  - ./extras/travis_push_docker_hub.sh
