# Default values for demo.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  metadata: 
      eureka: eureka-app
      key: key-app
      filedatabase: filedatabase-app
      res: res-app
      dataedge: dataedge-app      
      htsget: htsget-app    
      hystrix: hystrix-app                
  tag: stable
  pullPolicy: Always
  imageSecrets: regcredc 
  repository: 
      eureka:
        value: cscfi/netflix-eureka
        tag: "latest"
        port: 8761
        nodeport: 30761
        debug: 5061
        debugNodePort: 30001    
      key:
        value: cscfi/ega-keyserver
        tag: "latest"
        port: 9095
        nodeport: 30095
        debug: 5094
        debugNodePort: 30002      
      filedatabase:
        value: cscfi/ega-filedatabase
        tag: "latest"
        port: 9050
        nodeport: 30050
        debug: 5050
        debugNodePort: 30003   
      res:
        value: cscfi/ega-res
        tag: "latest"
        port: 9090
        nodeport: 30090
        debug: 5090
        debugNodePort: 30004
      dataedge:
        value: cscfi/ega-dataedge
        tag: "latest"
        port: 9059
        nodeport: 30059
        debug: 5059
        debugNodePort: 30005
      htsget:
        value: cscfi/ega-dataedge-htsget
        tag: "latest"
        port: 9060
        nodeport: 30060
        debug: 5060
        debugNodePort: 30006      
      hystrix:
        value: cscfi/netflix-hystrix
        tag: "latest"
        port: 8088
        nodeport: 30088
        debug: 5089
        debugNodePort: 30007

configService: "http://config.default.svc.cluster.local"

db:
  username: testuser
  password: testpassw0rd 
  url: "jdbc:postgresql://postgres.default.svc.cluster.local:5432/egapro"

s3:
  access: 
      key: test
      secret: test
      url: "https://test"
      region: europe

logdirectory:
  path: /tmp/logs
