# Default values for demo.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  metadata: 
      config: config-app
      postgres: postgres-app
  tag: stable
  pullPolicy: Always
  imageSecrets: regcredc 
  repository: 
      config:
        value: cscfi/netflix-config
        tag: "latest"
        port: 8888
      postgres:
        value: postgres
        tag: "10"
        port: 5432
        nodePort: 30432


logdirectory:
  path: /tmp/logs
